name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: ApiManagerApp.sln

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    - name: Upload build artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: Build Output Release
        path: |
          **/bin/Release/

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
  
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: Build Output Release
        path: release-artifacts
  
    - name: Archive compiled files
      run: |
        Compress-Archive -Path release-artifacts\* -DestinationPath release.zip
  
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: "Автоматическая сборка для Release-конфигурации"
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

